### ISSUE TITLE
semimtr_finetune without language model use

### ISSUE THREAD

**Issue by WongVi** [amazon-science/semimtr-text-recognition#12]
is it possible to fineture semimtr without trained language model use?
if possible please let me know how?
Thank you

**Comment by aaberdam** [comment]
Please elaborate more on why you don't want to use the language model. Is it due to its latency, or since you want to avoid pretraining of the language model.
If you want to reduce latency, you can work only with the vision model predictions (you can take a look here: `configs/semimtr_pretrain_vision_model.yaml`).
If you want to skip the pretraining of the language model, you can simply skip this stage and fine-tune the entire model, while the language model is initialized from scratch. This will decrease performance; however, if your train set is large enough, it won't be that significant.

**Comment by WongVi** [comment]
@aaberdam 
 I tried to run demo using your pretrained weight but I got error 
![image](https://user-images.githubusercontent.com/102502591/218365599-c011fc3f-f68b-4049-adeb-38b359318592.png)

1) how can I solve this error?
2) it is possible to use batch size image older in demo.py if possible please let me know how?

I tried to run demo.py with vision pretrained model only but got error 
![image](https://user-images.githubusercontent.com/102502591/218365822-3f62ec94-4c3a-471d-ba68-71f6fe509815.png)

 could you please let me know how can I solve?
